// ESLint flat config — https://eslint.org/docs/latest/use/configure/configuration-files-new
// Flat config replaces the legacy .eslintrc format. All plugins are imported as objects
// rather than loaded by string name, which makes the config portable and explicit.

import js from '@eslint/js';
import tsParser from '@typescript-eslint/parser';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import sveltePlugin from 'eslint-plugin-svelte';
import svelteParser from 'svelte-eslint-parser';
import globals from 'globals';

export default [
  js.configs.recommended,

  // TypeScript source files
  {
    files: ['src/**/*.ts'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        project: './tsconfig.json',
        extraFileExtensions: ['.svelte'],
      },
      // Browser globals: window, document, localStorage, navigator, etc.
      // These are available in all browser-targeted .ts files.
      globals: {
        ...globals.browser,
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      ...tsPlugin.configs['recommended'].rules,
      // Banning `any` enforces the use of `unknown` + type guards throughout the codebase,
      // which catches bugs that `any` would silently hide.
      '@typescript-eslint/no-explicit-any': 'error',
      // Non-null assertions (!) bypass TypeScript's null checks. They are banned unless
      // the developer explicitly acknowledges the risk with an inline disable comment.
      '@typescript-eslint/no-non-null-assertion': 'error',
      // Enforces `import type` for type-only imports so bundlers can tree-shake them out.
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
      // Unhandled promises are a common source of silent failures in event handlers.
      '@typescript-eslint/no-floating-promises': 'error',
      // Unused vars are errors (not warnings) to keep the codebase clean.
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      // Disallows await inside loops — usually indicates the loop should use Promise.all instead.
      // The rule is enabled so that individual uses can be explicitly allowed with a disable comment.
      'no-await-in-loop': 'error',
      'no-undef': 'off', // TypeScript handles this more accurately
    },
  },

  // Svelte component files — require both svelte-eslint-parser (for the template)
  // and @typescript-eslint/parser (for the <script> block)
  {
    files: ['src/**/*.svelte'],
    languageOptions: {
      parser: svelteParser,
      parserOptions: {
        parser: tsParser,
        project: './tsconfig.json',
        extraFileExtensions: ['.svelte'],
      },
      globals: {
        ...globals.browser,
      },
    },
    plugins: {
      svelte: sveltePlugin,
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      ...sveltePlugin.configs.recommended.rules,
      ...tsPlugin.configs['recommended'].rules,
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
      // no-floating-promises is intentionally relaxed in .svelte files because the Svelte
      // template compiler generates implicit promise chains for {#await} blocks.
      '@typescript-eslint/no-floating-promises': 'warn',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'svelte/valid-compile': 'error',
      // {@html} is used in Preview.svelte for Receipt.js SVG output — it is safe because
      // the SVG is generated by Receipt.js from ReceiptLine content, not raw user HTML.
      // Preview.svelte carries a file-level <!-- eslint-disable svelte/no-at-html-tags -->
      // comment to suppress the warning there specifically.
      'svelte/no-at-html-tags': 'error',
      'no-undef': 'off', // TypeScript handles this more accurately
    },
  },

  // Per-file overrides for Preview.svelte: allow {@html} because the SVG is generated
  // by Receipt.js from ReceiptLine source — not raw user-supplied HTML. svelte-eslint-parser
  // does not honour HTML-comment disable directives inside template blocks, so this config
  // override is the only reliable way to suppress the warning for exactly one file.
  {
    files: ['src/components/Preview.svelte'],
    rules: {
      'svelte/no-at-html-tags': 'off',
    },
  },

  // Config files at the root (vite.config.ts, vitest.config.ts, playwright.config.ts)
  // These are Node.js files, not browser files, and are excluded from the tsconfig project.
  {
    files: ['*.config.ts', '*.config.js'],
    languageOptions: {
      parser: tsParser,
      globals: {
        ...globals.node,
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },

  // Global ignores
  {
    ignores: ['dist/', 'node_modules/', 'public/lib/', '.vite/'],
  },
];
