<script lang="ts">
  import { toSVGDebounced, toSVG, isReceiptJsLoaded } from '$lib/receiptjs';
  import { resolve } from '$lib/variables';
  import { editorContent, printerSettings } from '$store/editorStore';
  import { csvRows, csvMode, previewRowIndex, setPreviewRowIndex } from '$store/placeholderStore';

  // $state() — svgOutput is reactive so the template re-renders when it changes.
  // The callback from toSVGDebounced updates this value asynchronously.
  let svgOutput = $state('');
  let isReceiptLoaded = $state(isReceiptJsLoaded());

  /**
   * $effect runs whenever editorContent, printerSettings, csvRows, csvMode, or
   * previewRowIndex changes. It computes the effective content to render:
   *
   *   - batch mode: resolve the content with the row at previewRowIndex
   *   - line-item mode: resolve the content with all rows as {{#items}}
   *   - no CSV: render the raw editor content
   *
   * Why $effect and not $derived?
   * This is a side effect — we are calling an external library (Receipt.js) and
   * writing to svgOutput via a callback. The 300 ms delay means the value does
   * not update synchronously with its inputs, which makes $derived unsuitable.
   * $derived must compute synchronously; $effect can schedule async work.
   */
  $effect(() => {
    const content = $editorContent;
    const settings = $printerSettings;
    const rows = $csvRows;
    const mode = $csvMode;
    const rowIndex = $previewRowIndex;

    // Check each render whether Receipt.js has loaded (it's a script tag,
    // so it may not be available on the very first render)
    isReceiptLoaded = isReceiptJsLoaded();

    if (!isReceiptLoaded) return;

    let effectiveContent: string;

    if (mode === 'batch' && rows.length > 0) {
      // Batch mode: show the resolved content for the currently selected row.
      // The row index is 0-based; setPreviewRowIndex clamps it to a valid range.
      const row = rows[rowIndex] ?? rows[0] ?? {};
      effectiveContent = resolve(content, { scalars: row });

      // In batch mode we want immediate feedback when navigating rows,
      // so skip debounce and render straight away.
      toSVG(effectiveContent, settings)
        .then((svg) => {
          svgOutput = svg;
        })
        .catch((err: unknown) => {
          if (import.meta.env.DEV) console.error('[Preview] toSVG batch error:', err);
        });
      return;
    } else if (mode === 'line-item' && rows.length > 0) {
      // Line-item mode: all rows form the {{#items}} block for a single receipt.
      effectiveContent = resolve(content, { items: rows });
    } else {
      effectiveContent = content;
    }

    toSVGDebounced(effectiveContent, settings, (svg) => {
      svgOutput = svg;
    });
  });

  // ---------------------------------------------------------------------------
  // Batch navigation handlers
  // ---------------------------------------------------------------------------

  function handlePrevRow(): void {
    setPreviewRowIndex($previewRowIndex - 1);
  }

  function handleNextRow(): void {
    setPreviewRowIndex($previewRowIndex + 1);
  }

  // Convenience derived values for the navigation bar
  let isBatchMode = $derived($csvMode === 'batch' && $csvRows.length > 0);
  let totalRows = $derived($csvRows.length);
  let currentRow = $derived($previewRowIndex + 1); // 1-based for display
</script>

<!-- eslint-disable svelte/no-at-html-tags -->
<!--
  Preview pane occupies the "preview" grid area.
  The SVG receipt is centred on a neutral grey background to suggest
  paper/roll context. See docs/design.md §10.5.
-->
<section class="preview-pane" aria-label="Receipt preview">
  <div class="preview-toolbar">
    <span class="toolbar-label">Preview</span>
    {#if $csvMode !== null}
      <span class="csv-mode-label">
        {$csvMode === 'batch' ? 'Batch mode' : 'Line-item mode'}
      </span>
    {/if}
  </div>

  <div class="preview-scroll">
    {#if !isReceiptLoaded}
      <!--
        Show a setup message when Receipt.js files are missing from public/lib/.
        This is expected during initial setup — the files must be downloaded
        from https://github.com/receiptline/receiptline (see public/lib/README.md).
      -->
      <div class="preview-placeholder">
        <p>Receipt.js is not loaded.</p>
        <p>Place <code>receipt.js</code> in <code>public/lib/</code> to enable preview.</p>
        <p>See <code>public/lib/README.md</code> for instructions.</p>
      </div>
    {:else if svgOutput === ''}
      <div class="preview-placeholder">
        <p>Start typing in the editor to see the receipt preview.</p>
      </div>
    {:else}
      <!--
        {#html} renders the SVG string directly into the DOM.
        This is safe here because the SVG is generated by Receipt.js from
        user-authored ReceiptLine content — it is not user-supplied raw HTML.
        The SVG only contains receipt graphics, not executable content.
      -->
      <div class="preview-content">
        {@html svgOutput}
      </div>
    {/if}
  </div>

  <!--
    Batch navigation bar — only shown in batch mode with multiple rows.
    Lets the user flip through CSV rows to visually verify each receipt
    before sending the batch to the printer.
    See docs/design.md §10.5.
  -->
  {#if isBatchMode}
    <div class="batch-nav" aria-label="Batch navigation">
      <button
        class="nav-btn"
        onclick={handlePrevRow}
        disabled={$previewRowIndex === 0}
        aria-label="Previous row"
      >
        ← Prev
      </button>

      <span class="row-indicator" aria-live="polite">
        Row {currentRow} of {totalRows}
      </span>

      <button
        class="nav-btn"
        onclick={handleNextRow}
        disabled={$previewRowIndex >= totalRows - 1}
        aria-label="Next row"
      >
        Next →
      </button>
    </div>
  {/if}
</section>

<style>
  .preview-pane {
    grid-area: preview;
    display: flex;
    flex-direction: column;
    overflow: hidden;
    background-color: var(--rd-color-preview-bg);
    border-right: 1px solid var(--rd-color-border);
  }

  .preview-toolbar {
    display: flex;
    align-items: center;
    gap: var(--rd-space-3);
    padding: var(--rd-space-2) var(--rd-space-3);
    border-bottom: 1px solid var(--rd-color-border);
    background-color: var(--rd-color-bg-secondary);
    flex-shrink: 0;
  }

  .toolbar-label {
    font-size: var(--rd-font-sm);
    color: var(--rd-color-text-secondary);
    font-weight: var(--rd-font-weight-medium);
  }

  .csv-mode-label {
    font-size: var(--rd-font-sm);
    color: var(--rd-color-placeholder);
    background-color: var(--rd-color-placeholder-bg);
    padding: 1px var(--rd-space-2);
    border-radius: var(--rd-radius-full);
    font-weight: var(--rd-font-weight-medium);
  }

  /* Scrollable container for the SVG receipt */
  .preview-scroll {
    flex: 1;
    overflow-y: auto;
    display: flex;
    justify-content: center;
    padding: var(--rd-space-6);
  }

  .preview-placeholder {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: var(--rd-space-2);
    color: var(--rd-color-text-secondary);
    font-size: var(--rd-font-base);
    text-align: center;
    max-width: 300px;
    margin: auto;
  }

  .preview-placeholder code {
    font-family: var(--rd-font-mono);
    font-size: var(--rd-font-sm);
    background-color: var(--rd-color-bg-tertiary);
    padding: 1px var(--rd-space-1);
    border-radius: var(--rd-radius-sm);
  }

  /* Centre the receipt SVG and give it a white paper background */
  .preview-content {
    background-color: var(--rd-color-bg-primary);
    box-shadow: var(--rd-shadow-md);
    border-radius: var(--rd-radius-sm);
    padding: var(--rd-space-4);
    align-self: flex-start;
  }

  /* The SVG generated by Receipt.js may set its own width — reset max-width
     so it doesn't overflow the preview pane on narrow screens.
     :global() is required because the SVG element is generated by Receipt.js,
     outside Svelte's scoped style system. */
  :global(.preview-content svg) {
    max-width: 100%;
    height: auto;
    display: block;
  }

  /*
   * Batch navigation bar — fixed to the bottom of the preview pane.
   * Uses Flexbox (1D alignment) for the row of buttons + indicator.
   */
  .batch-nav {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: var(--rd-space-4);
    padding: var(--rd-space-2) var(--rd-space-4);
    background-color: var(--rd-color-bg-secondary);
    border-top: 1px solid var(--rd-color-border);
    flex-shrink: 0;
  }

  .nav-btn {
    padding: var(--rd-space-1) var(--rd-space-3);
    font-size: var(--rd-font-sm);
    font-weight: var(--rd-font-weight-medium);
    background-color: var(--rd-color-bg-primary);
    border: 1px solid var(--rd-color-border-strong);
    border-radius: var(--rd-radius-sm);
    color: var(--rd-color-text-secondary);
    cursor: pointer;
    transition: background-color var(--rd-transition-fast);
  }

  .nav-btn:hover:not(:disabled) {
    background-color: var(--rd-color-bg-tertiary);
    color: var(--rd-color-text-primary);
  }

  .nav-btn:disabled {
    opacity: 0.4;
    cursor: not-allowed;
  }

  .row-indicator {
    font-size: var(--rd-font-sm);
    color: var(--rd-color-text-secondary);
    min-width: 80px;
    text-align: center;
  }
</style>
