<script lang="ts">
  import { toSVGDebounced, isReceiptJsLoaded } from '$lib/receiptjs';
  import { editorContent, printerSettings } from '$store/editorStore';

  // $state() — svgOutput is reactive so the template re-renders when it changes.
  // The callback from toSVGDebounced updates this value asynchronously.
  let svgOutput = $state('');
  let isReceiptLoaded = $state(isReceiptJsLoaded());

  /**
   * $effect runs whenever editorContent or printerSettings changes.
   * It calls toSVGDebounced, which waits 300 ms before rendering to avoid
   * calling Receipt.js on every single keystroke.
   *
   * Why $effect and not $derived?
   * This is a side effect — we are calling an external library (Receipt.js) and
   * writing to svgOutput via a callback. The 300 ms delay means the value does
   * not update synchronously with its inputs, which makes $derived unsuitable.
   * $derived must compute synchronously; $effect can schedule async work.
   */
  $effect(() => {
    const content = $editorContent;
    const settings = $printerSettings;

    // Check each render whether Receipt.js has loaded (it's a script tag,
    // so it may not be available on the very first render)
    isReceiptLoaded = isReceiptJsLoaded();

    if (!isReceiptLoaded) return;

    toSVGDebounced(content, settings, (svg) => {
      svgOutput = svg;
    });
  });
</script>

<!--
  Preview pane occupies the "preview" grid area.
  The SVG receipt is centred on a neutral grey background to suggest
  paper/roll context. See docs/design.md §10.5.
-->
<section class="preview-pane" aria-label="Receipt preview">
  <div class="preview-toolbar">
    <span class="toolbar-label">Preview</span>
  </div>

  <div class="preview-scroll">
    {#if !isReceiptLoaded}
      <!--
        Show a setup message when Receipt.js files are missing from public/lib/.
        This is expected during initial setup — the files must be downloaded
        from https://github.com/receiptline/receiptline (see public/lib/README.md).
      -->
      <div class="preview-placeholder">
        <p>Receipt.js is not loaded.</p>
        <p>Place <code>receipt.js</code> in <code>public/lib/</code> to enable preview.</p>
        <p>See <code>public/lib/README.md</code> for instructions.</p>
      </div>
    {:else if svgOutput === ''}
      <div class="preview-placeholder">
        <p>Start typing in the editor to see the receipt preview.</p>
      </div>
    {:else}
      <!--
        {#html} renders the SVG string directly into the DOM.
        This is safe here because the SVG is generated by Receipt.js from
        user-authored ReceiptLine content — it is not user-supplied raw HTML.
        The SVG only contains receipt graphics, not executable content.
      -->
      <div class="preview-content">
        {@html svgOutput}
      </div>
    {/if}
  </div>
</section>

<style>
  .preview-pane {
    grid-area: preview;
    display: flex;
    flex-direction: column;
    overflow: hidden;
    background-color: var(--rd-color-preview-bg);
    border-right: 1px solid var(--rd-color-border);
  }

  .preview-toolbar {
    display: flex;
    align-items: center;
    padding: var(--rd-space-2) var(--rd-space-3);
    border-bottom: 1px solid var(--rd-color-border);
    background-color: var(--rd-color-bg-secondary);
    flex-shrink: 0;
  }

  .toolbar-label {
    font-size: var(--rd-font-sm);
    color: var(--rd-color-text-secondary);
    font-weight: var(--rd-font-weight-medium);
  }

  /* Scrollable container for the SVG receipt */
  .preview-scroll {
    flex: 1;
    overflow-y: auto;
    display: flex;
    justify-content: center;
    padding: var(--rd-space-6);
  }

  .preview-placeholder {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: var(--rd-space-2);
    color: var(--rd-color-text-secondary);
    font-size: var(--rd-font-base);
    text-align: center;
    max-width: 300px;
    margin: auto;
  }

  .preview-placeholder code {
    font-family: var(--rd-font-mono);
    font-size: var(--rd-font-sm);
    background-color: var(--rd-color-bg-tertiary);
    padding: 1px var(--rd-space-1);
    border-radius: var(--rd-radius-sm);
  }

  /* Centre the receipt SVG and give it a white paper background */
  .preview-content {
    background-color: var(--rd-color-bg-primary);
    box-shadow: var(--rd-shadow-md);
    border-radius: var(--rd-radius-sm);
    padding: var(--rd-space-4);
    align-self: flex-start;
  }

  /* The SVG generated by Receipt.js may set its own width — reset max-width
     so it doesn't overflow the preview pane on narrow screens.
     :global() is required because the SVG element is generated by Receipt.js,
     outside Svelte's scoped style system. */
  :global(.preview-content svg) {
    max-width: 100%;
    height: auto;
    display: block;
  }
</style>
